### ISSUE TITLE
Server hangs

### ISSUE THREAD

**Issue by cssjunkie** [ryanaltvater/generator-liquid#3]
I installed and all seems well, but the served WP page stays blank and I can't establish a connection. I tried setting the wp-config to "debug=true" but that didn't do anything, so it's not the WP PHP hanging.

The browsersync page serves fine. Only the actual dev site hangs.

**Comment by cssjunkie** [comment]
The browsersync page serves fine. Only the actual dev site hangs.

**Comment by ryanaltvater** [comment]
@cssjunkie Wow, I'm really sorry I'm just now seeing this. I never received any notification of this post.

I believe you may have been experiencing a blank page after installing because you need to follow some additional steps on the backend of WP, listed out in the README. See below.

![screen shot 2018-03-23 at 10 49 20 am](https://user-images.githubusercontent.com/1336787/37836075-fde4b1f8-2e87-11e8-867d-19c740cd3738.png)

Thanks for checking Liquid out!
